import type { Metadata } from 'next';
import './globals.css';

import { Nunito } from 'next/font/google';
import { Providers } from '@/components/shared/Providers';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Next | Техно-Рост',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(nunito.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
